version: '3.8'

services:
  minitranslate:
    build: .
    container_name: minitranslate
    # Remove port mapping since nginx will handle external access
    # ports:
    #   - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
      # Persist users.json file
      - ./data/users.json:/app/users.json
    networks:
      - shared-network

  # Add nginx as the main reverse proxy
  nginx:
    image: nginx:alpine
    container_name: main-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:ro
      - ./nginx_conf/ssl:/etc/nginx/ssl:ro
    environment:
      - TZ=UTC
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - minitranslate
    networks:
      - shared-network

networks:
  shared-network:
    external: true 