version: '3.8'

services:
  translation-api:
    build: .
    container_name: chatgpt-translation-api
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
      # Persist users.json file
      - ./data/users.json:/app/users.json
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge 