version: "3.8"

services:
  vue-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vue-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  vue-frontend:
    build: .
    container_name: vue-alientranslate
    restart: unless-stopped
    depends_on:
      - vue-backend
    ports:
      - "8080:80"
