name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        default: 'v1.0.0'
        type: string
      release_title:
        description: 'Release title'
        required: false
        default: 'MiniTranslate Release'
        type: string
      release_notes:
        description: 'Release notes (optional)'
        required: false
        default: 'Bug fixes and improvements'
        type: string
      is_prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean
      is_draft:
        description: 'Create as draft release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o ./publish --self-contained true -r win-x64
    
    - name: Copy additional files
      run: |
        # Copy HTML files
        copy websites/translator.html publish\
        copy websites/translation-server.html publish\
        copy icon.ico publish\
        copy README.md publish\
        
        # Create docs directory if it doesn't exist and copy documentation
        if (!(Test-Path "publish\docs")) { New-Item -ItemType Directory -Path "publish\docs" -Force }
        copy docs\CHATGPT_SETUP.md publish\docs\
        copy docs\CHATGPT_API_SETUP.md publish\docs\
        copy docs\HOW_TO_USE.md publish\docs\
    
    - name: Create ZIP package
      run: |
        # Create a ZIP file with all necessary files
        Compress-Archive -Path "publish\*" -DestinationPath "MiniTranslate-Release.zip" -Force
    
    - name: List files for debugging
      run: |
        echo "Files in publish directory:"
        Get-ChildItem -Path "publish" -Recurse | ForEach-Object { Write-Host $_.FullName }
        echo "ZIP file created:"
        Get-ChildItem -Path "MiniTranslate-Release.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_version || github.ref_name }}
        name: ${{ github.event.inputs.release_title || 'MiniTranslate Release' }}
        body: |
          ## MiniTranslate Release
          
          ${{ github.event.inputs.release_notes || 'Bug fixes and improvements' }}
          
          ### What's New
          - Enhanced translation features
          - Improved user interface
          - Better language support
          
          ### Installation Instructions
          
          **Option 1: Download ZIP Package (Recommended)**
          1. Download `MiniTranslate-Release.zip`
          2. Extract all files to a folder
          3. Run `MiniTranslate.exe`
          4. Configure your preferred translation service
          
          **Option 2: Download Individual Files**
          If you prefer to download individual files, download all files from the release.
          
          ### Required Files
          - `MiniTranslate.exe` - Main application
          - `*.dll` files - .NET runtime libraries
          - `*.json` files - Configuration files
          - `*.html` files - Translation interfaces
          - `*.js` files - Web server components
          - `icon.ico` - Application icon
          - `README.md` - Basic documentation
          - `docs/` folder - Detailed setup guides
          
          ### Documentation
          See the `docs/` folder for detailed setup guides:
          - `HOW_TO_USE.md` - Complete user guide
          - `CHATGPT_SETUP.md` - ChatGPT API setup
          - `CHATGPT_API_SETUP.md` - Translation server setup
          
          ### System Requirements
          - Windows 10/11
          - No additional .NET installation required (self-contained)
        files: |
          MiniTranslate-Release.zip
          publish/MiniTranslate.exe
          publish/*.dll
          publish/*.json
          publish/*.html
          publish/*.js
          publish/icon.ico
          publish/README.md
          publish/docs/*.md
        draft: ${{ github.event.inputs.is_draft || false }}
        prerelease: ${{ github.event.inputs.is_prerelease || false }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}