name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        default: 'v1.0.0'
        type: string
      release_title:
        description: 'Release title'
        required: false
        default: 'MiniTranslate Release'
        type: string
      release_notes:
        description: 'Release notes (optional)'
        required: false
        default: 'Bug fixes and improvements'
        type: string
      is_prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean
      is_draft:
        description: 'Create as draft release'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o ./publish --self-contained true -r win-x64
    
    - name: Copy additional files
      run: |
        # Copy HTML files
        copy translator.html publish\
        copy translation-server.html publish\
        copy miniweb.js publish\
        copy icon.ico publish\
        copy README.md publish\
        
        # Create docs directory if it doesn't exist and copy documentation
        if (!(Test-Path "publish\docs")) { New-Item -ItemType Directory -Path "publish\docs" -Force }
        copy docs\CHATGPT_SETUP.md publish\docs\
        copy docs\CHATGPT_API_SETUP.md publish\docs\
        copy docs\HOW_TO_USE.md publish\docs\
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_version || github.ref_name }}
        name: ${{ github.event.inputs.release_title || 'MiniTranslate Release' }}
        body: |
          ## MiniTranslate Release
          
          ${{ github.event.inputs.release_notes || 'Bug fixes and improvements' }}
          
          ### What's New
          - Enhanced translation features
          - Improved user interface
          - Better language support
          
          ### Installation
          1. Download the `MiniTranslate.exe` file
          2. Run the executable
          3. Configure your preferred translation service
          
          ### Documentation
          See the `docs/` folder for detailed setup guides.
        files: |
          publish/MiniTranslate.exe
          publish/*.dll
          publish/*.json
          publish/*.html
          publish/*.js
          publish/icon.ico
          publish/README.md
          publish/docs/
        draft: ${{ github.event.inputs.is_draft || false }}
        prerelease: ${{ github.event.inputs.is_prerelease || false }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}