name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o ./publish --self-contained true -r win-x64
    
    - name: Copy additional files
      run: |
        # Copy HTML files
        copy translator.html publish\
        copy translation-server.html publish\
        copy miniweb.js publish\
        copy icon.ico publish\
        copy README.md publish\
        
        # Copy documentation
        mkdir publish\docs
        copy docs\CHATGPT_SETUP.md publish\docs\
        copy docs\CHATGPT_API_SETUP.md publish\docs\
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          publish/MiniTranslate.exe
          publish/*.dll
          publish/*.json
          publish/*.html
          publish/*.js
          publish/icon.ico
          publish/README.md
          publish/docs/
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}